services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app/app 
      - ./ml:/app/ml
      - ./data:/app/data
      - ./models:/app/models
    environment:
      # Corregir PYTHONPATH para incluir la carpeta app
      - PYTHONPATH=/app:/app/app:/app/ml
      - OMP_NUM_THREADS=4
      - TF_CPP_MIN_LOG_LEVEL=2
      - TENSORFLOW_INTER_OP_PARALLELISM_THREADS=4
      - TENSORFLOW_INTRA_OP_PARALLELISM_THREADS=4
    # Configuración de recursos para Mac
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G
    # Reiniciar automáticamente si falla
    restart: unless-stopped