version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./ml:/ml
      - ./data:/data
      - ./models:/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/app:/ml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]